### ISSUE TITLE
Android 8,9,10 - issue on emulator with getRealPathFromURI - NumberFormatException

### ISSUE THREAD

**Issue by Yurrili** [Wraptime/react-native-get-real-path#19]
Hi, I have issue with get image from downloads file on emulator.
My path: content://com.android.providers.downloads.documents/document/msf%3A253

And I've got this error:
` java.lang.NumberFormatException: For input string: "msf:253"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.valueOf(Long.java:808)
        at com.RNFetchBlob.Utils.PathResolver.getRealPathFromURI(PathResolver.java:47)`

Is it connected to testing on emulator?

 **I am using:**
> **Android:**
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
> **RN:**
>        "react": "16.9.0",
>        "react-native": "0.61.4",

**Comment by saadmutahar** [comment]
I'm getting the same error while selecting the pdf files from downloads on real device android S10.
pdf file from google drive working fine. Only facing issue when selecting from downloads folder. 

while selecting the doc file, below error coming...

Error copying Error: ENOENT: /storage/emulated/0/Download/file.doc: open failed: EACCES (Permission denied), open '/storage/emulated/0/Download/file.doc'

Is there any solution ? @p-ugulino @aleppos

**Comment by saadmutahar** [comment]
> Hi, I have issue with get image from downloads file on emulator.
> My path: content://com.android.providers.downloads.documents/document/msf%3A253
> 
> And I've got this error:
> ` java.lang.NumberFormatException: For input string: "msf:253"/ System.err: at java.lang.Long.parseLong(Long.java:594) W/System.err: at java.lang.Long.valueOf(Long.java:808) W/System.err: at com.rngrp.GRP.getRealPathFromURI(GRP.java:75)`
> 
> Is it connected to testing on emulator?
> 
> **I am using:**
> 
> > **Android:**
> > buildToolsVersion = "28.0.3"
> > minSdkVersion = 16
> > compileSdkVersion = 28
> > targetSdkVersion = 28
> > supportLibVersion = "28.0.0"
> > **RN:**
> > "react": "16.9.0",
> > "react-native": "0.61.4",

@Yurrili  found any solution?
